epc <-  read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=FALSE, dec=".")
febepc <- subset(epc,Date == "1/2/2007" | Date == "2/2/2007")
png(file="plot1.png",width = 480, height = 480, units = "px")
with(febepc,hist(as.numeric(Global_active_power),col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power"))
dev.off()